language: java
os: linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist: focal

jdk:  oraclejdk13

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql --version
  - psql -c 'SELECT version();'
  - psql -c 'CREATE DATABASE testdb;' -U postgres

env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/testdb

after_success:
  - ./gradlew check jacocoTestReport coveralls
