language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist: focal

jdk:  oraclejdk11

env: DATABASE_URL=postgres://postgres@localhost/pokemonteams

services: postgresql

before_script:
  - psql -c 'create database pokemonteams;' -U postgres

after_success:
  - gradle check jacocoTestReport coveralls
