language: java
os: linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist: focal

jdk:  oraclejdk13

services:
  - postgresql

addons:
  postgresql: '12.2'

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo service postgresql restart 12

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql --version
  - psql -c 'CREATE DATABASE testdb;' -U postgres

script:
  - psql -c 'SELECT version();'
  - ./gradlew build bootRun

env:
  - DATABASE_URL=postgres://postgres:@localhost:5432/testdb
  - global:
    - PGUSER=postgres
    - PGPORT=5432
    - PGPASSWORD=1234

after_success:
  - ./gradlew check jacocoTestReport coveralls
