language: java
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist: trusty

jdk:
  - oraclejdk13

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432
  - DATABASE_URL=postgres://postgres@localhost/pokemonteams

services:
  - postgresql

addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main

before_script:
  - psql -c 'create database pokemonteams;' -U postgres

after_success:
  - ./gradlew check jacocoTestReport coveralls
