language: java
os: linux

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

dist: focal

jdk: oraclejdk11

env:
  - global:
      - PGPORT=5433
      - DATABASE_URL=postgres://postgres:@localhost:5433/travis_ci_test

services:
  - postgresql

# Hardcode Postgres v12, so that it matches Heroku.
addons:
  postgresql: '12'
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql --version -p 5433
  - sudo sed -i 's/local   all             postgres                                peer/local   all             postgres                                trust/' /etc/postgresql/12/main/pg_hba.conf
  - sudo systemctl restart postgresql@12-main
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres -p 5433
  - psql -c 'SELECT datname FROM pg_database;' -U postgres -p 5433

script:
  - ./gradlew check --stacktrace

after_success:
  - ./gradlew check jacocoTestReport coveralls
